### ISSUE TITLE
Adding an XML happens even if the file is already in the UI folder and loads correctly. 

### ISSUE THREAD

**Issue by jessebevil** [macroquest/macroquest2#10]
UI file MQUI_PluginManagerWnd.xml added, you must reload your UI for this to take effect. 

But, it does this every time it loads, even when the window actually pops up.

Additionally, one must unload and then reload their plugin for the window to appear after the first time it's added and the UI is reloaded. 

Based on trying to load a plugin that has a window where the .xml file ISN'T found at all, then it means that there is already a system in place for finding if the file is present. It just appears it's not checked before outputting the message when it loads successfully. 

![image](https://user-images.githubusercontent.com/4873713/64499951-cab4bc80-d280-11e9-9204-1f04a6a1d789.png)

**Comment by jessebevil** [comment]
Looks like perhaps the base case isn't working as intended. 

```CPP
void AddXMLFile(const char* filename)
{
	for (const std::string& file : XmlFiles)
	{
		if (!_stricmp(file.c_str(), filename))
			return; // we already added this file
	}
```

**Comment by jessebevil** [comment]
![image](https://user-images.githubusercontent.com/4873713/64500831-80cdd580-d284-11e9-8d7d-13ad7b261215.png)

So I made a change that seems to have sorted it. I realized after my previous comment that the issue with the base case was not actually an issue as it appears to be adding it to a list of already loaded XML files. 

Instead, to prevent the message I edited the following. 

```CPP
	DebugSpew("Adding XML File %s", filename);
	if (gGameState == GAMESTATE_INGAME)
	{
		sprintf_s(szBuffer, "uifiles\\default\\%s", filename);
		if (!DoesFileExist(szBuffer)) {
			WriteChatf("UI file %s added, you must reload your UI for this to take effect.", filename);
		}
	}
```
in the output, to check to see if the file was present prior to outputting the information about adding it, but it still allows it to do the XmlFiles.emplace_back(filename); at the end of the function.

**Comment by brainiac** [comment]
Regarding reloading the plugin and seeing the message despite having the UI load: this only happens if you unload/reload the plugin multiple times in the same session. The reason why it works is because EQ already has loaded the XML data for that UI, and keeps it around, even after the plugin has unloaded. If you were to reloadui in between unloading and reloading, you would go through the same process of having to reloadui again.

Checking if the XML file exists isn't a solution to the problem. What matters is if EQ has loaded the XML file into memory. reloading the UI is what does that.

AddXMLFile assumes that any XML file that is being added hasn't already been loaded by EQ, because that is the far more common case.

This is working as intended. We could go and check if the XML has been loaded already but I'm not sure its worth the effort.

**Comment by jessebevil** [comment]
okay, that makes more sense then.
